# Generated by Django 2.2.4 on 2021-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='applicantincome',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='coapplicatincome',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='credithistory',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='dependants',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='loanamt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='loanterm',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='totalincome',
            field=models.BigIntegerField(default=0),
        ),
    ]
